### ISSUE TITLE
Access control origin

### ISSUE THREAD

**Issue by ccachor** [glennreyes/fetch-instagram#1]
How can this be tested locally? I'm getting CORS error, but not sure I can specify * to Instagram API regardless. Is this module meant to run in Node or the browser?

**Comment by glennreyes** [comment]
It should work just fine locally with all CORS requests enabled, both in Node and browser.

**Comment by mares29** [comment]
i had also this problem. Check this https://stackoverflow.com/a/6083677/6679875 (only for development ;) )

**Comment by glennreyes** [comment]
Thank you @mares29
